### ISSUE TITLE
Paginated Search is missing

### ISSUE THREAD

**Issue by abubakarflutter** [OutdatedGuy/firebase_pagination#22]
Would you please add search with pagination please

**Comment by OutdatedGuy** [comment]
@abubakarflutter, can you elaborate your question more. Please provide a brief and detailed explanation.

**Comment by abubakarflutter** [comment]
I have a collection of all products "all-products" with 10k documents in it.
with the help of this package, I can simply get pagination of all the products using any orderBy condition.
But when I want to search for any product (normally the "product_name") based on my query in text field. 
I know there is a method
.where('product_name' , isEqualTo: "queryText")  
but this is not what i want
I want the docs with contains user queryText

So while search any product there migth be hundreds of docs contains queryText in product_name , but I want those docs in limit of 10 or 20 etc rather displaying all those 

Hope, you are understood

**Comment by OutdatedGuy** [comment]
Ok, thanks for the explanation. However, I'm still quite not clear about what you want though.

1. [ ] You want to filter pre-fetched docs by the package with the `queryText` the user enters. So no more records will be loaded but the only pre-loaded docs will be filtered with the `queryText`.

2. [x] You want to search/filter docs with the `queryText` and paginate them with the package. So instead of paginating all the docs, the package will only paginate the docs filtered using `queryText`.

3. [ ] Not any of the above (please comment and tell more specific details)

**Comment by abubakarflutter** [comment]
Yes exactly like the second one

**Comment by OutdatedGuy** [comment]
@abubakarflutter, I searched a lot regarding your feature request, however it's not something this package should do. This package is only for pagination and live listener purpose.

However, you can implement it by passing your query to `FirestorePagination` widget as shown in this SO [comment](https://stackoverflow.com/a/56815787).

Closing as not planned
