### ISSUE TITLE
Fetch Data from Firebase Realtime Database in Descending Order[Feature Request] 

### ISSUE THREAD

**Issue by CodeWithBishal** [OutdatedGuy/firebase_pagination#33]
Is it possible to fetch data using RealtimeDBPagination in Descending Order?

Basically I want my latest data to be on the top of the screen and older to the bottom of the screen.

A walkthrough would be appreciated.

Thanks,

**Comment by CodeWithBishal** [comment]
changed _data with _data.toList().reversed.toList() works fine for me. We can ask if data should be reversed in the widget and define it as 

`widget.reverseData ? _data.toList().reversed.toList() : _data`

We also gotta change:

``var docsQuery = widget.reverseData
        ? widget.query.limitToLast(docsLimit)
        : widget.query.limitToFirst(docsLimit);``

should I create a PR?

**Comment by OutdatedGuy** [comment]
@CodeWithBishal, yeah the problem is Firebase Realtime Database doesn't support decending `orderBy`.

I'm quite busy right now, so PRs are welcomed.

### Just heads up

I'm **currently** not actively maintaining this particular package. So instead I would suggest using the [official firebase pagination package for realtime database](https://pub.dev/packages/firebase_ui_database).
